deploy:
  provider: npm
  email: 296240671@qq.com
  api_key:
    secure: wNDu19R72U8U42Wr/tp22aQQFvnKnBXouFupBvUviqZ0hoUnQDAWF19TOAHGX54SLxtKcwOGCkxnvrZEsfgfbna5QHwZwBc83knMz51tG25mc9Y2R8nScv6HKky1mlMI7Ka94useFg4mPo2Wy/Q2eGHCmaA+2pY+V+HdRHKRsqkom9r1MWSd9ZWaeE9NSlfYgWjVpxPeSk8DxN3GbG+ekHXVyi2J3QgDyRjjrnmeHI5HvgodAE73SouXOv48n6OhqBd5/RN6UfwxdhiPSLDDaP73VdzNdR6hU5EeODJ6xEjhsKm89sy/SVQNW9XOCKH6Y3lCYk/BkUQlUIkFE/YClCXvnQWgIeMYc55lKvfu0zqXIXNaoQviZKXteeqIT2+YeuSTMxBhLeC8HMpfJFBdyfXrNh3WM0mAYZlTjS+XpBm1nyMhk8ZX4u/s5SILGM3qY57QN9Ah+BEA+6HjKNw98fSOVGf05qZVZRMsMO3HZyUArOAq6hwP60gAunx7Haf2RJidzxH/TWItXvZNAYylnhQcda8aNLQPUxiY+wVkOVrzEgAXMUxFaHuG08kK9CZZpAiL4P/XDjYsU4K0n4+0Ix7i6+HPryZ0qKvlv3QgDpnyxzQrLidsWYlNKOzv+nYepJrc1mupOvYaBIce6dcJHTei6VOY4HGzVfn6HJbO7BE=
  on:
    branch: master
